### ISSUE TITLE
Adding multiple pointers.

### ISSUE THREAD

**Issue by everythinginjs** [loput12ouj35/React-slide-rule#16]
Hello @loput12ouj35  thanks for the useful repo, I wish I could do something like the image I attached.

I needed to add ranges that shows min and max of a normal parameter along with the min and max of the whole ruler I tried adding them within the cursor props but all of the sudden, realised value can be above the orange min ad max.

<img width="212" alt="Screenshot 2023-10-09 at 7 31 05 pm" src="https://github.com/loput12ouj35/React-slide-rule/assets/34276557/0e7d4031-705c-439b-885e-7e152141ac14">

**Comment by everythinginjs** [comment]
I think for more flexibility developers might need to add marks not two but as many as they want.

**Comment by everythinginjs** [comment]
Do you accept any PRs, I have gone through the code base and I think there are a lot to fix and improve the code base ?
1. Functional components.
2. Ability to add marks as many as user would like.
3. fixing and improving ts.

**Comment by loput12ouj35** [comment]
Hello @everythinginjs ,
sorry for the late reply and thank you for watching this project carefully 😆

We accept PRs, of course. Any PR would be helpful for the projects!
